### ISSUE TITLE
範例15.8中可能遺漏了一個無窮迴圈

### ISSUE THREAD

**Issue by fanofxiaofeng** [JustinSDK/JavaSE6Tutorial#16]
範例15.8後面的文字中提到

> 因為 SomeThread 中的 run() 方法有個無窮迴圈。

不過範例15.8中似乎遺漏了這個**無窮迴圈**
![61d63deb-2d09-474f-82f0-ba8e8a626d36](https://cloud.githubusercontent.com/assets/3983683/24827413/a712fa5c-1c7b-11e7-86b7-ca5e5a4d2308.png)

**Comment by JustinSDK** [comment]
modified
