### ISSUE TITLE
調整格式

### ISSUE THREAD

**Issue by obelisk0114** [JustinSDK/JavaSE6Tutorial#28]
有一些以雙引號標示起來的部分是否考慮改用 markdown 的語法 ?
以第 20 章的內容為例

原文
"鍵（Key）"對應的"值（Value）"

調整為
`鍵（Key）`對應的`值（Value）`
或是
**鍵（Key）** 對應的 **值（Value）**

**Comment by JustinSDK** [comment]
這份文件是開放的，如果覺得可以增加可讀性，你可以協助調整。
