### ISSUE TITLE
第十三章內文

### ISSUE THREAD

**Issue by homeisme** [JustinSDK/JavaSE6Tutorial#33]
經提醒，是本人出錯，而非書中內容問題。謝謝。

另外感謝老師的文章，內容都很豐富而順暢，細讀每一章都可以深入了解每種JAVA內存在的意義，讓學生受益良多，希望未來能有機會能看到老師出 C# 的技術手冊。

**Comment by jyhsu2000** [comment]
這不算矛盾吧
兩者實作的介面不同
一個是 Sorted**Set**，一個是 Sorted**Map**

**Comment by homeisme** [comment]
抱歉，是我看錯了。謝謝提醒。

> 這不算矛盾吧
> 兩者實作的介面不同
> 一個是 Sorted**Set**，一個是 Sorted**Map**
