### ISSUE TITLE
範例 15.14 Clerk.java 的 getProduct

### ISSUE THREAD

**Issue by obelisk0114** [JustinSDK/JavaSE6Tutorial#35]
`範例 15.14` Clerk.java 的 `public synchronized int getProduct()` 使用 int 回傳, 但是我在其他部分並未看出有使用到這個回傳值
請問能否改用 `void` 回傳 ?

**Comment by JustinSDK** [comment]
這是個開放性討論問題，你可以在其他討論區與人討論看看，issue 建議用於問題回報。
