### ISSUE TITLE
 ThreadGroup 使用時機與安全性

### ISSUE THREAD

**Issue by johnyluyte** [JustinSDK/JavaSE6Tutorial#4]
您好，

關於第 15 章 [執行緒（Thread）](https://github.com/JustinSDK/JavaSE6Tutorial/blob/master/docs/CH15.md) 的 15.1.7 ThreadGroup 有些問題想請教，

我對 ThreadGroup 的使用時機感到困惑，因此上網搜尋了一下，請參閱這幾篇討論：

- [What is the benefit of ThreadGroup in java over creating separate threads?](http://stackoverflow.com/questions/1649133/what-is-the-benefit-of-threadgroup-in-java-over-creating-separate-threads)

- [Why ThreadGroup is being criticised?](http://stackoverflow.com/questions/3265640/why-threadgroup-is-being-criticised)

- [THI01-J. Do not invoke ThreadGroup methods](https://www.securecoding.cert.org/confluence/display/java/THI01-J.+Do+not+invoke+ThreadGroup+methods)

這幾篇討論都建議我們避免使用 ThreadGroup API，應改用 [Executors](http://docs.oracle.com/javase/7/docs/api/java/util/concurrent/Executors.html)，且 `ThreadGroup.activeCount()` 與 `ThreadGroup.enumerate()` 被列為 insecure 的 API，不知您對於現在(Java 1.6 ~ 1.8) ThreadGroup 的使用時機有何看法呢？謝謝。

**Comment by JustinSDK** [comment]
印象中看過一些類似建議，採用 executor 是比較好的做法。
2015/7/25 下午2:42於 "Chun Chien" <notifications@github.com>寫道：

**Comment by johnyluyte** [comment]
好的，感謝回應。
